bhhan:
  username: "Hello Shipping"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
oauth2:
  jwtSigningKey: HelloWorld
logging:
  level:
    root: info  
